spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:stats-db
    username: admin
    password: 100

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    #    hibernate:
    #      ddl-auto: create-drop

    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect

